# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DFlight_Import
                                 A QGIS plugin
 Converte in geopackage ed importa il file Json relativo alle Geo Zone scaricabile da D-Flight
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-09-02
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Antonio Di Marco/ARPAT
        email                : a.dimarco@arpat.toscana.it
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import json
import re
import traceback
import platform
import subprocess
from datetime import datetime

from qgis.PyQt.QtCore import QLocale, QTranslator, QCoreApplication, QVariant, QFileInfo, Qt
from qgis.core import (
    QgsSettings, QgsProject, QgsVectorLayer, QgsField, QgsFeature,
    QgsGeometry, QgsPointXY, QgsCoordinateReferenceSystem, QgsVectorFileWriter
)
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QFileDialog, QMessageBox, QApplication

# Import the code for the dialog
from .dflight_import_dialog import DFlight_ImportDialog


class DFlight_Import:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor."""
        self.iface = iface
        self.plugin_dir = os.path.dirname(__file__)
        
        locale = QgsSettings().value('locale/userLocale', QLocale().name())[0:2]
        locale_path = os.path.join(self.plugin_dir, 'i18n', '{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        self.actions = []
        self.menu = self.tr(u'&Importa UAS Geo Zone di D-Flight')
        self.first_start = None

    def tr(self, message):
        """Get the translation for a string using Qt translation API."""
        return QCoreApplication.translate('DFlight_Import', message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar."""
        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)
        if whats_this is not None:
            action.setWhatsThis(whats_this)
        if add_to_toolbar:
            self.iface.addToolBarIcon(action)
        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)
        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""
        icon_path = os.path.join(os.path.dirname(__file__), 'icon.png')
        self.add_action(
            icon_path,
            text=self.tr(u'Importa zone DFlight'),
            callback=self.run,
            parent=self.iface.mainWindow())
        self.first_start = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(self.tr(u'&Importa UAS Geo Zone di D-Flight'), action)
            self.iface.removeToolBarIcon(action)

    def run(self):
        """Run method that performs all the real work."""
        # Ignoriamo la dialog default del Plugin Builder e avviamo direttamente la tua logica
        run_import()


# ==============================================================================
# LOGICA DEL TUO SCRIPT (Funzioni di supporto)
# ==============================================================================

def create_log_file(base_path):
    """Crea percorso univoco per file di log"""
    base, _ = os.path.splitext(base_path)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    return f"{base}_log_{timestamp}.txt"


def log_to_file(log_path, message, mode='a'):
    """Scrivi nel file di log"""
    try:
        with open(log_path, mode, encoding='utf-8') as f:
            f.write(message + "\n")
    except Exception as e:
        print(f"⚠️ Errore scrittura log: {e}")


def parse_json_file(json_path, log_path):
    """Parsa file JSON con fallback multi-strategia"""
    log_to_file(log_path, "="*70)
    log_to_file(log_path, f"PARSING: {json_path}")
    log_to_file(log_path, f"Dimensione file: {os.path.getsize(json_path):,} byte")
    log_to_file(log_path, "="*70)
    
    try:
        with open(json_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        log_to_file(log_path, "✓ File letto correttamente")
        
        # Strategia 1: JSON valido standard
        try:
            data = json.loads(content)
            if isinstance(data, dict) and 'features' in data:
                features = data['features']
                log_to_file(log_path, f"✓ Trovata chiave 'features': {len(features)} elementi")
                return features
            elif isinstance(data, list):
                log_to_file(log_path, f"✓ Array radice: {len(data)} elementi")
                return data
        except Exception as e:
            log_to_file(log_path, f"✗ Strategia 1 fallita: {str(e)[:100]}")
        
        # Strategia 2: Estrai array features con regex
        log_to_file(log_path, "\nStrategia 2: ricerca array 'features' con regex...")
        match = re.search(r'"features"\s*:\s*(\[[\s\S]*\])', content)
        if match:
            try:
                features_str = match.group(1)
                features = json.loads(features_str)
                log_to_file(log_path, f"✓ Estratte {len(features)} features con regex")
                return features
            except Exception as e:
                log_to_file(log_path, f"✗ Regex fallita: {str(e)[:100]}")
        
        # Strategia 3: Estrai oggetti JSON concatenati (JSON Lines)
        log_to_file(log_path, "\nStrategia 3: parsing oggetti JSON concatenati...")
        objects = []
        brace_count = 0
        start_idx = -1
        
        for i, char in enumerate(content):
            if char == '{':
                if brace_count == 0:
                    start_idx = i
                brace_count += 1
            elif char == '}':
                brace_count -= 1
                if brace_count == 0 and start_idx != -1:
                    try:
                        obj_str = content[start_idx:i+1]
                        obj = json.loads(obj_str)
                        if isinstance(obj, dict) and ('identifier' in obj or 'geometry' in obj):
                            objects.append(obj)
                        start_idx = -1
                    except:
                        pass
        
        if objects:
            log_to_file(log_path, f"✓ Estratti {len(objects)} oggetti validi")
            return objects
        
        raise Exception("Nessuna strategia di parsing riuscita. File non riconosciuto.")
    
    except Exception as e:
        log_to_file(log_path, f"\n✗ ERRORE FATALE: {str(e)}")
        log_to_file(log_path, f"Traceback:\n{traceback.format_exc()}")
        raise


def create_layer(features, layer_name, log_path):
    """Crea layer vettoriale con campi originali e logging dettagliato"""
    log_to_file(log_path, "\n" + "="*70)
    log_to_file(log_path, "CREAZIONE LAYER VETTORIALE")
    log_to_file(log_path, "="*70)
    log_to_file(log_path, f"Features totali: {len(features)}")
    
    layer = QgsVectorLayer("Polygon?crs=epsg:4326", layer_name, "memory")
    provider = layer.dataProvider()
    
    fields = [
        QgsField("identifier", QVariant.String),
        QgsField("country", QVariant.String),
        QgsField("name", QVariant.String),
        QgsField("type", QVariant.String),
        QgsField("restriction", QVariant.String),
        QgsField("reason", QVariant.String),
        QgsField("otherReasonInfo", QVariant.String),
        QgsField("authority_name", QVariant.String),
        QgsField("authority_email", QVariant.String),
        QgsField("authority_phone", QVariant.String),
        QgsField("permanent", QVariant.String),
        QgsField("lowerLimit", QVariant.Double),
        QgsField("upperLimit", QVariant.Double),
        QgsField("lowerVerticalReference", QVariant.String),
        QgsField("upperVerticalReference", QVariant.String),
        QgsField("uomDimensions", QVariant.String)
    ]
    
    provider.addAttributes(fields)
    layer.updateFields()
    
    feats = []
    skipped = []
    imported = 0
    processed = 0
    
    for idx, item in enumerate(features):
        processed += 1
        try:
            geometries = item.get('geometry', [])
            if not isinstance(geometries, list):
                geometries = [geometries]
            
            if not geometries:
                skipped.append(f"Feature {idx} (ID: {item.get('identifier', 'N/A')}): nessuna geometria")
                continue
            
            for gidx, geom_data in enumerate(geometries):
                if not isinstance(geom_data, dict):
                    skipped.append(f"Feature {idx} (ID: {item.get('identifier', 'N/A')}), geom[{gidx}]: geometria non è dict")
                    continue
                
                lower_limit = float(geom_data.get('lowerLimit', 0))
                upper_limit = float(geom_data.get('upperLimit', 120))
                lower_ref = str(geom_data.get('lowerVerticalReference', 'AGL'))
                upper_ref = str(geom_data.get('upperVerticalReference', 'AGL'))
                uom = str(geom_data.get('uomDimensions', 'M'))
                
                proj = geom_data.get('horizontalProjection', {})
                coords = proj.get('coordinates', [])
                
                if not coords:
                    skipped.append(f"Feature {idx} (ID: {item.get('identifier', 'N/A')}), geom[{gidx}]: coordinates vuoto")
                    continue
                
                rings = []
                if isinstance(coords, list) and coords:
                    if isinstance(coords[0], list) and coords[0] and isinstance(coords[0][0], list):
                        for ring in coords:
                            if isinstance(ring, list) and len(ring) >= 3:
                                points = []
                                for pt in ring:
                                    if isinstance(pt, list) and len(pt) >= 2:
                                        try:
                                            points.append(QgsPointXY(float(pt[0]), float(pt[1])))
                                        except:
                                            pass
                                if len(points) >= 3:
                                    rings.append(points)
                    elif isinstance(coords[0], list) and len(coords[0]) >= 2:
                        points = []
                        for pt in coords:
                            if isinstance(pt, list) and len(pt) >= 2:
                                try:
                                    points.append(QgsPointXY(float(pt[0]), float(pt[1])))
                                except:
                                    pass
                        if len(points) >= 3:
                            rings = [points]
                
                if not rings or len(rings[0]) < 3:
                    skipped.append(f"Feature {idx} (ID: {item.get('identifier', 'N/A')}), geom[{gidx}]: anello < 3 punti")
                    continue
                
                geom = QgsGeometry.fromPolygonXY(rings)
                if geom.isEmpty():
                    skipped.append(f"Feature {idx} (ID: {item.get('identifier', 'N/A')}), geom[{gidx}]: geometria vuota")
                    continue
                
                reason = item.get('reason', [])
                reason_str = ';'.join(reason) if isinstance(reason, list) else str(reason)
                
                auth_list = item.get('zoneAuthority', [])
                auth = auth_list[0] if auth_list and isinstance(auth_list[0], dict) else {}
                
                app_list = item.get('applicability', [])
                perm = app_list[0].get('permanent', 'N/A') if app_list and isinstance(app_list[0], dict) else 'N/A'
                
                feat = QgsFeature()
                feat.setGeometry(geom)
                feat.setAttributes([
                    str(item.get('identifier', f'feat_{idx}_{gidx}')),
                    str(item.get('country', 'ITA')),
                    str(item.get('name', 'Unnamed')),
                    str(item.get('type', 'COMMON')),
                    str(item.get('restriction', 'REQ_AUTHORISATION')),
                    reason_str,
                    str(item.get('otherReasonInfo', '')),
                    str(auth.get('name', 'N.A.')),
                    str(auth.get('email', 'N.A.')),
                    str(auth.get('phone', 'N.A.')),
                    str(perm),
                    lower_limit,
                    upper_limit,
                    lower_ref,
                    upper_ref,
                    uom
                ])
                
                feats.append(feat)
                imported += 1
        
        except Exception as e:
            skipped.append(f"Feature {idx} (ID: {item.get('identifier', 'N/A')}): eccezione - {str(e)[:120]}")
            continue
    
    if feats:
        provider.addFeatures(feats)
        layer.updateExtents()
    
    log_to_file(log_path, f"\nStatistiche:")
    log_to_file(log_path, f"  • Features processate: {processed}")
    log_to_file(log_path, f"  • Geometrie importate: {imported}")
    log_to_file(log_path, f"  • Geometrie saltate: {len(skipped)}")
    
    if skipped:
        log_to_file(log_path, f"\nDettaglio geometrie saltate (prime 50):")
        for i, msg in enumerate(skipped[:50]):
            log_to_file(log_path, f"  {i+1}. {msg}")
        if len(skipped) > 50:
            log_to_file(log_path, f"  ... altre {len(skipped)-50} geometrie saltate")
    
    return layer, imported, len(skipped), skipped


def run_import():
    """Funzione principale di importazione"""
    print("\n" + "="*70)
    print("AVVIO IMPORTAZIONE ZONE DRONI/UAS")
    print("="*70)
    
    json_path, _ = QFileDialog.getOpenFileName(
        None, "Seleziona file JSON con zone droni", "", "JSON Files (*.json *.geojson)"
    )
    
    if not json_path:
        print("❌ Annullato dall'utente")
        return
    
    print(f"✓ File selezionato: {os.path.basename(json_path)}")
    
    log_path = create_log_file(json_path)
    log_to_file(log_path, "LOG IMPORTAZIONE ZONE DRONI/UAS (formato ATM09)", 'w')
    log_to_file(log_path, f"Data: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    log_to_file(log_path, f"File input: {json_path}")
    
    try:
        QApplication.setOverrideCursor(Qt.WaitCursor)
        features = parse_json_file(json_path, log_path)
        print(f"✓ Parsing completato: {len(features)} features trovate")
    except Exception as e:
        QApplication.restoreOverrideCursor()
        QMessageBox.critical(None, "Errore parsing", f"Impossibile parsare il file:\n{str(e)}")
        print(f"❌ Errore parsing: {e}")
        return
    
    try:
        layer_name = f"Zone_Droni_{os.path.splitext(os.path.basename(json_path))[0][:30]}"
        layer, imported, skipped_count, skipped_list = create_layer(features, layer_name, log_path)
        
        if imported == 0:
            QApplication.restoreOverrideCursor()
            QMessageBox.warning(None, "Nessuna geometria", 
                               f"Nessuna geometria valida trovata.\nLog: {log_path}")
            return
        
        print(f"✓ Layer creato: {imported} geometrie importate, {skipped_count} saltate")
    except Exception as e:
        QApplication.restoreOverrideCursor()
        QMessageBox.critical(None, "Errore creazione layer", f"{str(e)}\n\nLog: {log_path}")
        print(f"❌ Errore creazione layer: {e}\n{traceback.format_exc()}")
        return
    
    default_out = os.path.splitext(json_path)[0] + "_qgis.gpkg"
    print("➡️  Selezione percorso salvataggio...")
    output_path, _ = QFileDialog.getSaveFileName(
        None, "Salva come GeoPackage", default_out, "GeoPackage (*.gpkg)"
    )
    
    QApplication.restoreOverrideCursor()
    
    if not output_path:
        # APPLICA LO STILE PREDEFINITO
        style_path = os.path.join(os.path.dirname(__file__), 'styles', 'STILE D FLIGHT AGGIORNATO.qml')
        if os.path.exists(style_path):
            layer.loadNamedStyle(style_path)
            layer.triggerRepaint()
        
        QgsProject.instance().addMapLayer(layer)
        QMessageBox.information(None, "Layer caricato", 
            f"Layer '{layer.name()}' aggiunto al progetto.\n"
            f"Geometrie: {imported} importate, {skipped_count} saltate\n"
            f"Log: {log_path}")
        print(f"ℹ️  Layer aggiunto al progetto (salvataggio annullato)")
        return
    
    if not output_path.lower().endswith('.gpkg'):
        output_path += '.gpkg'
    
    log_to_file(log_path, f"\nFile output: {output_path}")
    
    try:
        print("➡️  Salvataggio layer...")
        options = QgsVectorFileWriter.SaveVectorOptions()
        options.driverName = "GPKG"
        options.fileEncoding = "UTF-8"
        
        error = QgsVectorFileWriter.writeAsVectorFormatV3(
            layer, output_path, QgsProject.instance().transformContext(), options
        )
        
        if error[0] != QgsVectorFileWriter.NoError:
            raise Exception(f"Errore OGR: {error[1]}")
        
        # Carica layer salvato
        saved_layer = QgsVectorLayer(output_path, QFileInfo(output_path).baseName(), "ogr")
        if not saved_layer.isValid():
            raise Exception("Layer salvato non valido")
        
        # APPLICA LO STILE PREDEFINITO
        style_path = os.path.join(os.path.dirname(__file__), 'styles', 'STILE D FLIGHT AGGIORNATO.qml')
        if os.path.exists(style_path):
            saved_layer.loadNamedStyle(style_path)
            saved_layer.triggerRepaint()
        
        QgsProject.instance().addMapLayer(saved_layer)
        
        tmp = QgsProject.instance().mapLayersByName(layer_name)
        if tmp:
            QgsProject.instance().removeMapLayer(tmp[0].id())
        
        msg = (f"✅ File salvato con successo:\n{output_path}\n\n"
               f"📊 Geometrie importate: {imported}\n"
               f"📊 Geometrie saltate: {skipped_count}\n\n"
               f"📄 Log dettagliato:\n{log_path}")
        
        QMessageBox.information(None, "Completato", msg)
        print(f"\n✅ COMPLETATO")
        print(f"   File: {output_path}")
        print(f"   Geometrie: {imported} importate / {skipped_count} saltate")
        print(f"   Log: {log_path}")
        
        # Apertura log cross-platform (Windows, macOS, Linux)
        if skipped_count > 0:
            reply = QMessageBox.question(None, "Geometrie saltate", 
                f"{skipped_count} geometrie sono state saltate.\n"
                f"Vuoi aprire il file di log per vedere i dettagli?",
                QMessageBox.Yes | QMessageBox.No)
            if reply == QMessageBox.Yes:
                if platform.system() == 'Darwin':       # macOS
                    subprocess.call(('open', log_path))
                elif platform.system() == 'Windows':    # Windows
                    os.startfile(log_path)
                else:                                   # Linux
                    subprocess.call(('xdg-open', log_path))
    
    except Exception as e:
        QMessageBox.warning(None, "⚠️ Salvataggio parziale", 
            f"Errore salvataggio:\n{str(e)}\n\n"
            f"Il layer è stato comunque aggiunto al progetto in memoria.\n"
            f"Log: {log_path}")
        QgsProject.instance().addMapLayer(layer)
        print(f"⚠️ Salvataggio fallito: {e}")
