# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DFlight_Import
                                 A QGIS plugin
 Converts the Geo Zone JSON file downloadable from D-Flight to GeoPackage and imports it
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-09-03
        copyright            : (C) 2026 by Antonio Di Marco/Dimadrones
        email                : dimarco71@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DFlight_Import class from file DFlight_Import.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .dflight_import import DFlight_Import
    return DFlight_Import(iface)
